server:
  port: 9003

spring:
  application:
    name: cloudalibaba-provider-cluster
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.177.66:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'