server:
  port: 8401

spring:
  application:
    name: sentinel-server8401

  cloud:
    nacos:
      discovery:
        server-addr: 120.25.177.66:1111
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，键入被占用会自动从8719+1，直到找到未被占用的端口
        port: 8791
      web-context-unify: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
