server:
  port: 8001

spring:
  application:
    name: eurekaClient8001

eureka:
  client:
    #表示是否将自己注册到进eurekaServer默认为true
    register-with-eureka: true
    #是否从eureka中抓取已有的注册消息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://center.appint.cn/eureka/
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true
    # 主机名称修改
    instance-id: consumer8001
    # eurekaClient 向注册中心发送心跳的时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 30
    # 注册中心收到最后一次心跳的时间上限，默认90秒，超时将被剔除
    lease-expiration-duration-in-seconds: 90
