server:
  port: 8006

spring:
  application:
    name: client-consul8006

  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，介于0到1之间，1表示全部采样
      probability: 1